# Generated by Django 5.2.18 on 2026-10-06 16:42

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0003_remove_motivo_criado_por_delete_historicalmotivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstornoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(db_index=True, verbose_name='Data do estorno')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('contato_cliente', models.CharField(help_text='Telefone ou e-mail', max_length=100, verbose_name='Contato do cliente')),
                ('data_venda', models.DateField(verbose_name='Data da venda')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='O valor precisa ser maior que zero.')], verbose_name='Valor')),
                ('nsu', models.CharField(db_index=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\d+$', 'O NSU deve conter apenas números.')], verbose_name='NSU')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('solicitado_banco', models.BooleanField(default=False, verbose_name='Solicitado no Safra')),
                ('conciliado', models.BooleanField(default=False, verbose_name='Conciliado (EJL)')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estornos', to='cadastros.loja', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Estorno de cartão',
                'verbose_name_plural': 'Estornos de cartão',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEstornoCartao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(db_index=True, verbose_name='Data do estorno')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('contato_cliente', models.CharField(help_text='Telefone ou e-mail', max_length=100, verbose_name='Contato do cliente')),
                ('data_venda', models.DateField(verbose_name='Data da venda')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='O valor precisa ser maior que zero.')], verbose_name='Valor')),
                ('nsu', models.CharField(db_index=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\d+$', 'O NSU deve conter apenas números.')], verbose_name='NSU')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('solicitado_banco', models.BooleanField(default=False, verbose_name='Solicitado no Safra')),
                ('conciliado', models.BooleanField(default=False, verbose_name='Conciliado (EJL)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.loja', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'historical Estorno de cartão',
                'verbose_name_plural': 'historical Estornos de cartão',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
