# Generated by Django 5.2.18 on 2026-10-06 19:07

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0003_remove_motivo_criado_por_delete_historicalmotivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLinkPagamento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(db_index=True, verbose_name='Data')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('parcelas', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'O mínimo é 1 parcela.'), django.core.validators.MaxValueValidator(24, 'O máximo é 24 parcelas.')], verbose_name='Parcelamento')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='O valor precisa ser maior que zero.')], verbose_name='Valor')),
                ('nsu', models.CharField(blank=True, db_index=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\d+$', 'O NSU deve conter apenas números.')], verbose_name='NSU')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('no_caixa', models.BooleanField(default=False, verbose_name='No caixa')),
                ('nc_assinada', models.BooleanField(default=False, verbose_name='Nota de crédito assinada')),
                ('doc_enviado', models.BooleanField(default=False, verbose_name='Documentação enviada')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'historical Link de pagamento',
                'verbose_name_plural': 'historical Links de pagamento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LinkPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(db_index=True, verbose_name='Data')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('parcelas', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'O mínimo é 1 parcela.'), django.core.validators.MaxValueValidator(24, 'O máximo é 24 parcelas.')], verbose_name='Parcelamento')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='O valor precisa ser maior que zero.')], verbose_name='Valor')),
                ('nsu', models.CharField(blank=True, db_index=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\d+$', 'O NSU deve conter apenas números.')], verbose_name='NSU')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('no_caixa', models.BooleanField(default=False, verbose_name='No caixa')),
                ('nc_assinada', models.BooleanField(default=False, verbose_name='Nota de crédito assinada')),
                ('doc_enviado', models.BooleanField(default=False, verbose_name='Documentação enviada')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='cadastros.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Link de pagamento',
                'verbose_name_plural': 'Links de pagamento',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
