# Generated by Django 5.2.17 on 2026-10-05 17:30

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_alter_motivo_motivo_unico_por_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucaoPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(db_index=True, verbose_name='Data')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='O valor precisa ser maior que zero.')], verbose_name='Valor')),
                ('conciliado', models.BooleanField(default=False, verbose_name='Conciliado (EJL)')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes_pix', to='cadastros.banco', verbose_name='Banco')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes_pix', to='cadastros.loja', verbose_name='Loja')),
                ('motivo', models.ForeignKey(limit_choices_to={'tipo': 'PIX'}, on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes_pix', to='cadastros.motivo', verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Devolução de Pix',
                'verbose_name_plural': 'Devoluções de Pix',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDevolucaoPix',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(db_index=True, verbose_name='Data')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='O valor precisa ser maior que zero.')], verbose_name='Valor')),
                ('conciliado', models.BooleanField(default=False, verbose_name='Conciliado (EJL)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('banco', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.banco', verbose_name='Banco')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.loja', verbose_name='Loja')),
                ('motivo', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'tipo': 'PIX'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.motivo', verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'historical Devolução de Pix',
                'verbose_name_plural': 'historical Devoluções de Pix',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
