# Generated by Django 5.2.17 on 2026-10-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucaopix',
            name='motivo',
            field=models.CharField(max_length=255, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='historicaldevolucaopix',
            name='motivo',
            field=models.CharField(default='', max_length=255, verbose_name='Motivo'),
            preserve_default=False,
        ),
    ]
