# Generated by Django 5.2.17 on 2026-10-01 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='motivo',
            name='motivo_unico_por_tipo',
            constraint=models.UniqueConstraint(fields=('descricao', 'tipo'), name='motivo_unico_por_tipo', violation_error_message='Esse motivo já está cadastrado para este tipo.'),
        ),
        migrations.AlterConstraint(
            model_name='vendedor',
            name='vendedor_unico_por_loja',
            constraint=models.UniqueConstraint(fields=('nome', 'loja'), name='vendedor_unico_por_loja', violation_error_message='Já existe um vendedor com esse nome nesta loja.'),
        ),
    ]
