# Generated by Django 5.2.17 on 2026-10-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_motivo_motivo_unico_por_tipo_and_more'),
        ('pix', '0002_alter_devolucaopix_motivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivo',
            name='criado_por',
        ),
        migrations.DeleteModel(
            name='HistoricalMotivo',
        ),
        migrations.DeleteModel(
            name='Motivo',
        ),
    ]
